[package]
name = "rusty-bank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guid-create = "0.2.0"
rql = "0.5.2"
chrono = "0.4"
serde = "1.0.137"